### PR TITLE
CharacterCounter

### PR DESCRIPTION
**Pull request by Chaitanya-2804**
Hey This project was made by me when I was learning javascript. This also uses HTML and CSS obviously but the main reason for me to do is to learn javascript.

### CODE REVIEW

**Review by mrkc2303 — APPROVED** [review]

**Comment by yellowberard** [comment]
Please rename 8_character_count

**Comment by yellowberard** [comment]
- If you have any link to access the project please include that also.

**Comment by mrkc2303** [comment]
@Chaitanya-2804 Please update the Folder Name to PascalCase!!

**Comment by Chaitanya-2804** [comment]
I didn't undestood.
I have uploaded the whole project with .html , .css and .js files

**Pull request merged**
