### PR TITLE
TicTacToe added

### PR DESCRIPTION
**Pull request by iamharshvardhan**
This commit contains all the files and screenshots!

### CODE REVIEW

**Comment by mrkc2303** [comment]
I can only see the folder, not the files and ss. Kindly check

**Comment by mrkc2303** [comment]
Screenshot 2022-10-05 at 10 15 26 PM

**Comment by KushagraJain58-cmd** [comment]
The folder is empty. Kindly check

**Comment by iamharshvardhan** [comment]
Fixing the issues..

**Pull request closed without merging**
