### PR TITLE
Adding chat app

### PR DESCRIPTION
**Pull request by VINAYBOYAT11**

### CODE REVIEW

**Comment by VINAYBOYAT11** [comment]
please check out my pull request

**Comment by VINAYBOYAT11** [comment]
thankyou

**Review by mrkc2303 — CHANGES_REQUESTED** [review]
All files are empty having no code. Kindly update that.
Also please rename the folder namr in PascalCase, i.e, ChatApp and MusicWebsite in your case.

**Comment by VINAYBOYAT11** [comment]
@server-geeks i made some changes can you please check out 
also i added all files codes

**Comment by mrkc2303** [comment]
Folder Name is still not in PascalCase, i.e, Chat App -> ChatApp.
Kindly Correct that.
Rest all seems good

**Comment by KushagraJain58-cmd** [comment]
LGTM!!

**Comment by VINAYBOYAT11** [comment]
finally .. could you please merge it..?

**Comment by VINAYBOYAT11** [comment]
thank you @mrkc2303  and @KushagraJain58-cmd

**Pull request merged**
