### PR TITLE
Add Contributors section in readme.md

### PR DESCRIPTION
**Pull request by Vani177**
Hey, I've added a Contributors section in README.md, I hope it's a good change.
Kindly add the hacktoberfest label to the issue as if you merge the forked repo.
Thanks!

### CODE REVIEW

**Comment by Vani177** [comment]
> Can you please add it after maintainers.

sure, of course, at it!

**Comment by Vani177** [comment]
done, you can check it out

**Comment by yellowberard** [comment]
Thanks for your contribution!!

**Review by yellowberard — APPROVED** [review]

**Comment by yellowberard** [comment]
Can you do the same in our DSA repository @Vani177 .

**Comment by Vani177** [comment]
> Can you do the same in our DSA repository @Vani177 .

sure, of course!

**Comment by Vani177** [comment]
> Thanks for your contribution!!

glad to contribute!!

**Pull request merged**
