### PR TITLE
added zomato-clone website (frontend) and a screenshot of the live site.

### PR DESCRIPTION
**Pull request by ranodeepbanerjee**

### CODE REVIEW

**Comment by KushagraJain58-cmd** [comment]
Kindly changes the file name in PascalCase. In your case zomato-clone should be ZomatoClone

**Comment by ranodeepbanerjee** [comment]
@KushagraJain58-cmd Done sir!

**Comment by yellowberard** [comment]
Please put all the files in a single folder name ZomatoClone

**Comment by mrkc2303** [comment]
@ranodeepbanerjee Kindly add all the files into the same folder. 
Delete the unnecessary directory named zomato-clone.

**Comment by ranodeepbanerjee** [comment]
@mrkc2303 @yellowberard Done sir! kindly Check.

**Pull request merged**
