### PR TITLE
WeddingWebsite

### PR DESCRIPTION
**Pull request by Prankit1**
I have added the frontend of wedding planner  and also added some screenshots of my website.

### CODE REVIEW

**Comment by yellowberard** [comment]
Please rename the file in pascal casing i.e. WeddingWebsite

**Review by Prankit1 — COMMENTED** [review]
Changes the file name in pascal

**Comment by mrkc2303** [comment]
Changes aren't Reflected, Change the directory name which contains your code into PascalCase
@Prankit1

**Review by Prankit1 — COMMENTED** [review]
I have changed my directory name in PascalCase

**Review by mrkc2303 — APPROVED** [review]
LGTM!

**Pull request merged**
